package models

var google = map[string]CatalogModel{
	"chat-bison-001":                     {Name: "chat-bison-001", Type: ModelTypeText},
	"chat-bison-002":                     {Name: "chat-bison-002", Type: ModelTypeText},
	"codegemma-2b":                       {Name: "codegemma-2b", Type: ModelTypeText},
	"codegemma-7b":                       {Name: "codegemma-7b", Type: ModelTypeText},
	"gemini-1.5-flash":                   {Name: "gemini-1.5-flash", Type: ModelTypeText},
	"gemini-1.5-flash-001":               {Name: "gemini-1.5-flash-001", Type: ModelTypeText},
	"gemini-1.5-flash-002":               {Name: "gemini-1.5-flash-002", Type: ModelTypeText},
	"gemini-1.5-flash-8b":                {Name: "gemini-1.5-flash-8b", Type: ModelTypeText},
	"gemini-1.5-pro":                     {Name: "gemini-1.5-pro", Type: ModelTypeText},
	"gemini-1.5-pro-001":                 {Name: "gemini-1.5-pro-001", Type: ModelTypeText},
	"gemini-1.5-pro-002":                 {Name: "gemini-1.5-pro-002", Type: ModelTypeText},
	"gemini-2.5-flash":                   {Name: "gemini-2.5-flash", Type: ModelTypeText},
	"gemini-2.5-flash-latest":            {Name: "gemini-2.5-flash-latest", Type: ModelTypeText},
	"gemini-2.5-flash-lite":              {Name: "gemini-2.5-flash-lite", Type: ModelTypeText},
	"gemini-2.5-pro":                     {Name: "gemini-2.5-pro", Type: ModelTypeText},
	"gemini-2.5-pro-latest":              {Name: "gemini-2.5-pro-latest", Type: ModelTypeText},
	"gemini-3-flash-preview":             {Name: "gemini-3-flash-preview", Type: ModelTypeText},
	"gemini-3.1-flash-lite":              {Name: "gemini-3.1-flash-lite", Type: ModelTypeText},
	"gemini-3.1-pro-preview":             {Name: "gemini-3.1-pro-preview", Type: ModelTypeText},
	"gemini-3.1-pro-preview-customtools": {Name: "gemini-3.1-pro-preview-customtools", Type: ModelTypeText},
	"gemini-3.5-flash":                   {Name: "gemini-3.5-flash", Type: ModelTypeText},
	"gemini-3.5-flash-lite":              {Name: "gemini-3.5-flash-lite", Type: ModelTypeText},
	"gemini-3.6-flash":                   {Name: "gemini-3.6-flash", Type: ModelTypeText},
	"gemini-3.6-flash-latest":            {Name: "gemini-3.6-flash-latest", Type: ModelTypeText},
	"gemma-2-27b":                        {Name: "gemma-2-27b", Type: ModelTypeText},
	"gemma-2-2b":                         {Name: "gemma-2-2b", Type: ModelTypeText},
	"gemma-2-9b":                         {Name: "gemma-2-9b", Type: ModelTypeText},
	"gemma-3-12b":                        {Name: "gemma-3-12b", Type: ModelTypeText},
	"gemma-3-1b":                         {Name: "gemma-3-1b", Type: ModelTypeText},
	"gemma-3-27b":                        {Name: "gemma-3-27b", Type: ModelTypeText},
	"gemma-3-4b":                         {Name: "gemma-3-4b", Type: ModelTypeText},
	"recurrentgemma-2b":                  {Name: "recurrentgemma-2b", Type: ModelTypeText},
	"text-bison-001":                     {Name: "text-bison-001", Type: ModelTypeText},
	"text-bison-002":                     {Name: "text-bison-002", Type: ModelTypeText},
}
