syntax = "proto3";
package proto;
option go_package = "github.com/HyperToken-dev/fabric/gen;proto";
import "google/protobuf/timestamp.proto";

service ApiKeyAdminService {
    rpc CreateApiKey(CreateAdminApiKeyRequest) returns(CreateAdminApiKeyResponse);
    rpc RevokeApiKey(RevokeAdminApiKeyRequest) returns(RevokeAdminApiKeyResponse);
    rpc ListApiKeys(ListAdminApiKeysRequest) returns(ListAdminApiKeysResponse);
    rpc ListApiKeysByChannelID(ListAdminApiKeysByChannelIDRequest) returns(ListAdminApiKeysResponse);
    rpc ListApiKeysByChannelName(ListAdminApiKeysByChannelNameRequest) returns(ListAdminApiKeysResponse);
}

message AdminApiKey {
    string key_name = 1;
    string key_hash = 2;
    string raw_key = 3;
    google.protobuf.Timestamp created_at = 4;
    int32 key_id = 5;
    int32 channel_id = 6;
    string channel_name = 7;
    string owner_openid = 8;
}

message CreateAdminApiKeyRequest {
    string key_name = 1;
    int32 channel_id = 2;
}

message CreateAdminApiKeyResponse {
    AdminApiKey api_key = 1;
}

message RevokeAdminApiKeyRequest {
    string key_hash = 1;
}

message RevokeAdminApiKeyResponse {}

message ListAdminApiKeysRequest {}

message ListAdminApiKeysByChannelIDRequest {
    int32 channel_id = 1;
}

message ListAdminApiKeysByChannelNameRequest {
    string channel_name = 1;
}

message ListAdminApiKeysResponse {
    repeated AdminApiKey api_keys = 1;
}
