syntax = "proto3";
package proto;
option go_package = "hyper-token/gen;proto";
import "google/protobuf/timestamp.proto";

service ChannelService {
    rpc CreateChannel(CreateChannelRequest) returns(CreateChannelResponse);
    rpc ListChannels(ListChannelsRequest) returns(ListChannelsResponse);
}

message Channel {
    int32 channel_id = 1;
    string channel_name = 2;
    google.protobuf.Timestamp created_at = 3;
}

message ListChannelsRequest {}

message ListChannelsResponse {
    repeated Channel channels = 1;
}

message CreateChannelRequest {
    string channel_name = 1;
}

message CreateChannelResponse {
    Channel channel = 1;
}