syntax = "proto3";
package proto;
option go_package = "github.com/HyperToken-dev/fabric/gen;proto";

service ModelAdminService {
    rpc GetModelInfo(GetAdminModelInfoRequest) returns(GetAdminModelInfoResponse);
    rpc CreateModel(CreateAdminModelRequest) returns(CreateAdminModelResponse);
    rpc ListModels(ListAdminModelsRequest) returns(ListAdminModelsResponse);
    rpc ListCatalogModels(ListCatalogModelsRequest) returns(ListCatalogModelsResponse);
}

message AdminModel {
    int32 model_id = 1;
    string model_name = 2;
    int32 channel_id = 3;
    int32 status = 4;
    int32 model_type = 5;
}

message CatalogModel {
    string model_name = 1;
    int32 model_type = 2;
}

message GetAdminModelInfoRequest {
    int32 model_id = 1;
}

message GetAdminModelInfoResponse {
    AdminModel model = 1;
}

message ListAdminModelsRequest {
    int32 channel_id = 1;
}

message ListAdminModelsResponse {
    repeated AdminModel models = 1;
}

message ListCatalogModelsRequest {
    int32 api_format = 1;
}

message ListCatalogModelsResponse {
    repeated CatalogModel models = 1;
}

message CreateAdminModelRequest {
    string model_name = 1;
    int32 channel_id = 2;
    int32 status = 3;
    int32 model_type = 4;
}

message CreateAdminModelResponse {
    AdminModel model = 1;
}
