proxyAddr: 3002
adminAddr: 9090
logLevel: info

timeZone: Asia/Shanghai

db:
  addr: postgres
  user: root
  port: 5432
  dbName: fabric
  password: "123456" # important!change your password when needed!
  maxIdle: 20
  maxOpen: 100
  maxLifeTime: 1h

log:
  maxSize: 100
  maxBackups: 10
  maxAge: 30
  compress: true

oauth:
  enabled: true
  issuerURL: "http://casdoor.localhost:8000/.well-known/openid-configuration"
  clientID: "e289d5f6a25fee57ef2e" # Default
  clientSecret: "6beb0ea6fe3cbbf6ec2d3853860ad8e68c013fd7" # Default
  redirectURL: "http://localhost:9090/auth/callback" # path should always /auth/callback
  scopes:
    - openid
    - email
    - profile
  sessionSecret: "37c7d2f241dd5f4f4c629ebf9da151e96ea9eb2db52b934dd22c7b186c5f64c2" # Change this secret if needed
  allowedDomains: []
  adminEmails: [admin@example.com] # Change this email address if needed
  autoProvision: true
  defaultRole: user
