package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"

	"github.com/HyperToken-dev/fabric/business/sensitive"
	"github.com/HyperToken-dev/fabric/internal/adminauth"
	"github.com/HyperToken-dev/fabric/internal/config"
	"github.com/HyperToken-dev/fabric/internal/models"
	"github.com/HyperToken-dev/fabric/internal/repository"
	"github.com/HyperToken-dev/fabric/internal/router"
	"github.com/HyperToken-dev/fabric/internal/server"
	"github.com/HyperToken-dev/fabric/internal/service"
	"github.com/HyperToken-dev/fabric/internal/storage/postgres"
	webui "github.com/HyperToken-dev/fabric/internal/web"
	"github.com/HyperToken-dev/fabric/logger"

	pbconnect "github.com/HyperToken-dev/fabric/gen/protoconnect"

	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/lib/pq"
	"github.com/spf13/viper"
	"go.uber.org/zap"
)

func main() {
	// get workDir
	path, err := os.Executable()
	if err != nil {
		log.Fatalf("Get working directory error: %v", err)
	}
	workDir := filepath.Dir(path)

	// get runPath
	runPath, err := os.Getwd()
	if err != nil {
		log.Fatalf("Get run path error: %v", err)
	}

	// init viper
	viper.SetConfigName("config")
	viper.SetConfigType("yaml")
	viper.AddConfigPath(filepath.Join(runPath, "configs"))
	viper.AddConfigPath(workDir)
	viper.AddConfigPath(".")
	if err := viper.ReadInConfig(); err != nil {
		log.Fatalf("Can not read in config file: %v", err)
	}

	// init config
	cfg, err := config.Load(workDir, runPath)
	if err != nil {
		log.Fatalf("load config file error: %v", err)
	}

	// init zap
	zapLogger, err := logger.NewLogger(cfg)
	if err != nil {
		log.Fatalf("init zap logger error: %v", err)
	}
	zap.ReplaceGlobals(zapLogger)
	defer func() {
		if err := zapLogger.Sync(); err != nil {
			log.Printf("sync logger error: %v", err)
		}
	}()
	zap.L().Info("configuration loaded",
		zap.String("proxy_addr", cfg.ProxyAddr),
		zap.String("admin_addr", cfg.AdminAddr),
	)

	// init sensitive word detect
	sensitiveRuntimeStore := service.NewSensitiveRuntimeStore(sensitiveRuntimePath(workDir, runPath))
	if err := sensitiveRuntimeStore.Ensure(context.Background()); err != nil {
		zap.S().Fatalf("init sensitive runtime store error: %v", err)
	}
	sensitiveSource := gatewaySensitiveSource{runtimeStore: sensitiveRuntimeStore}
	textPolicy := sensitive.NewReloadablePolicy(sensitive.Snapshot{})
	loaded, err := sensitiveSource.State(context.Background())
	if err != nil {
		zap.S().Fatalf("load sensitive dictionaries error: %v", err)
	}
	textPolicy = sensitive.NewReloadablePolicy(sensitive.Snapshot{
		Enabled:         loaded.Enabled,
		Detector:        loaded.Detector,
		DictionaryCount: loaded.DictionaryCount,
	})
	zap.L().Info("sensitive runtime store loaded",
		zap.String("path", sensitiveRuntimeStore.StatePath()),
		zap.Bool("enabled", loaded.Enabled),
		zap.Int("count", loaded.DictionaryCount),
	)

	// db con str
	dsn := config.GetDSN(cfg.DB)

	// migrate
	zap.L().Info("database migration started")
	if err := runMigrations(dsn); err != nil {
		zap.S().Warnf("migration warning: %v", err)
	} else {
		zap.L().Info("database migration completed")
	}

	// init db engine
	db, err := sql.Open("postgres", dsn)
	if err != nil {
		zap.S().Fatalf("failed to open database: %v", err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		zap.S().Fatalf("failed to ping database: %v", err)
	}
	db.SetMaxIdleConns(cfg.DB.MaxIdle)
	db.SetMaxOpenConns(cfg.DB.MaxOpen)
	db.SetConnMaxLifetime(cfg.DB.MaxLifeTime)
	zap.L().Info("database connected",
		zap.Int("max_idle", cfg.DB.MaxIdle),
		zap.Int("max_open", cfg.DB.MaxOpen),
		zap.Duration("max_lifetime", cfg.DB.MaxLifeTime),
	)

	// repo generated by sqlc
	queries := repository.New(db)

	apiKeySvc := service.NewApiKeyService(db)
	channelSvc := service.NewChannelService(db)
	modelSvc := service.NewModelService(db)
	usageSvc := service.NewUsageService(db, cfg.Location)
	integralLogSvc := service.NewIntegralLogService(db)
	sensitiveWordSvc := service.NewSensitiveWordService(sensitiveRuntimeStore, textPolicy, sensitiveSource.State)
	srv := server.NewServer(apiKeySvc, channelSvc, modelSvc, usageSvc, integralLogSvc, sensitiveWordSvc)
	clientSrv := server.NewClientServer(apiKeySvc, channelSvc, modelSvc)

	// register proxy
	proxyStore := postgres.NewProxyStore(db)
	openaiProxy, err := NewOpenAIProxy(OpenAIProxyOptions{
		ModelStore:         newModelStoreAdapter(proxyStore),
		UsageHandler:       newOpenAIUsageAdapter(proxyStore),
		IntegralLogHandler: newIntegralLogAdapter(proxyStore),
		TextPolicy:         textPolicy,
	})
	if err != nil {
		zap.S().Fatalf("create openai proxy error: %v", err)
	}
	alibabaBailianProxy, err := NewAlibabaBailianProxy(AlibabaBailianProxyOptions{
		ModelStore:         newModelStoreAdapter(proxyStore),
		IntegralLogHandler: newIntegralLogAdapter(proxyStore),
	})
	if err != nil {
		zap.S().Fatalf("create alibaba bailian proxy error: %v", err)
	}
	seedanceProxy, err := NewSeedanceProxy(SeedanceProxyOptions{
		ModelStore:         newModelStoreAdapter(proxyStore),
		IntegralLogHandler: newIntegralLogAdapter(proxyStore),
		ProviderTaskStore:  newProviderTaskStoreAdapter(proxyStore),
		TextPolicy:         textPolicy,
	})
	if err != nil {
		zap.S().Fatalf("create seedance proxy error: %v", err)
	}
	googleProxy, err := NewGoogleProxy(GoogleProxyOptions{
		ModelStore:         newModelStoreAdapter(proxyStore),
		UsageHandler:       newGoogleUsageAdapter(proxyStore),
		IntegralLogHandler: newIntegralLogAdapter(proxyStore),
		TextPolicy:         textPolicy,
	})
	if err != nil {
		zap.S().Fatalf("create google proxy error: %v", err)
	}
	extrotecProxy, err := NewExtrotecProxy(ExtrotecProxyOptions{
		ModelStore:         newModelStoreAdapter(proxyStore),
		IntegralLogHandler: newIntegralLogAdapter(proxyStore),
		TextPolicy:         textPolicy,
	})
	if err != nil {
		zap.S().Fatalf("create extrotec proxy error: %v", err)
	}

	rt := router.New(queries, map[int32]router.Proxy{
		models.APIFormatOpenAI:         openaiProxy,
		models.APIFormatAlibabaBailian: alibabaBailianProxy,
		models.APIFormatSeedance:       seedanceProxy,
		models.APIFormatGoogle:         googleProxy,
		models.APIFormatExtrotec:       extrotecProxy,
	})
	proxyMux := rt.RegisterProxyRoutes()
	zap.L().Info("proxy routes registered")

	go func() {
		zap.S().Infof("Proxy server listening on %s", cfg.ProxyAddr)
		if err := http.ListenAndServe(cfg.ProxyAddr, proxyMux); err != nil {
			zap.S().Fatalf("proxy server: %v", err)
		}
	}()

	adminMux := http.NewServeMux()
	apiKeyPath, apiKeyHandler := pbconnect.NewApiKeyAdminServiceHandler(srv)
	apiKeyClientPath, apiKeyClientHandler := pbconnect.NewApiKeyClientServiceHandler(clientSrv)
	usagePath, usageHandler := pbconnect.NewUsageServiceHandler(srv)
	channelPath, channelHandler := pbconnect.NewChannelAdminServiceHandler(srv)
	channelClientPath, channelClientHandler := pbconnect.NewChannelClientServiceHandler(clientSrv)
	modelPath, modelHandler := pbconnect.NewModelAdminServiceHandler(srv)
	modelClientPath, modelClientHandler := pbconnect.NewModelClientServiceHandler(clientSrv)
	integralLogPath, integralLogHandler := pbconnect.NewIntegralLogServiceHandler(srv)
	sensitivePath, sensitiveHandler := pbconnect.NewSensitiveWordServiceHandler(srv)
	var adminHandler http.Handler = adminMux
	var cookieManager *adminauth.CookieManager
	if cfg.OAuth.Enabled {
		oauthManager, err := adminauth.NewManager(db, cfg.OAuth)
		if err != nil {
			zap.S().Fatalf("create oidc auth manager error: %v", err)
		}
		cookieManager = adminauth.NewCookieManager(cfg.OAuth.SessionSecret, adminauth.SecureCookie(cfg.OAuth.RedirectURL))
		authHandler := adminauth.NewHandler(db, oauthManager, cookieManager)
		adminMux.HandleFunc("/auth/login", authHandler.Login)
		adminMux.HandleFunc("/auth/callback", authHandler.Callback)
		adminHandler = authHandler.Middleware(adminMux)
		zap.L().Info("oidc auth enabled", zap.String("issuer_url", cfg.OAuth.IssuerURL))
	} else {
		systemUser, err := adminauth.SystemUser(context.Background(), db)
		if err != nil {
			zap.S().Fatalf("load system auth user error: %v", err)
		}
		adminHandler = systemUserMiddleware(adminMux, systemUser)
		zap.L().Warn("oidc auth disabled; admin server uses built-in system user")
	}
	authPath, authServiceHandler := pbconnect.NewAuthServiceHandler(adminauth.NewService(cookieManager, cfg.OAuth.Enabled))
	adminMux.Handle(authPath, authServiceHandler)
	adminMux.Handle(apiKeyPath, apiKeyHandler)
	adminMux.Handle(apiKeyClientPath, apiKeyClientHandler)
	adminMux.Handle(usagePath, usageHandler)
	adminMux.Handle(channelPath, channelHandler)
	adminMux.Handle(channelClientPath, channelClientHandler)
	adminMux.Handle(modelPath, modelHandler)
	adminMux.Handle(modelClientPath, modelClientHandler)
	adminMux.Handle(integralLogPath, integralLogHandler)
	adminMux.Handle(sensitivePath, sensitiveHandler)
	zap.L().Info("admin handlers registered",
		zap.String("auth_path", authPath),
		zap.String("api_key_path", apiKeyPath),
		zap.String("api_key_client_path", apiKeyClientPath),
		zap.String("usage_path", usagePath),
		zap.String("channel_path", channelPath),
		zap.String("channel_client_path", channelClientPath),
		zap.String("model_path", modelPath),
		zap.String("model_client_path", modelClientPath),
		zap.String("integral_log_path", integralLogPath),
		zap.String("sensitive_path", sensitivePath),
	)

	zap.S().Infof("Admin server listening on %s", cfg.AdminAddr)
	if err := http.ListenAndServe(cfg.AdminAddr, webui.Handler(adminHandler)); err != nil {
		zap.S().Fatalf("admin server: %v", err)
	}
}

func systemUserMiddleware(next http.Handler, user repository.User) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(w, r.WithContext(adminauth.WithUser(r.Context(), user)))
	})
}

func runMigrations(databaseURL string) error {
	m, err := migrate.New("file://db/migrations", databaseURL)
	if err != nil {
		return fmt.Errorf("migrate init: %w", err)
	}
	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
		return fmt.Errorf("migrate up: %w", err)
	}
	return nil
}
