package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"

	openaiusage "fabric/business/usage/openai"
	"fabric/internal/config"
	"fabric/internal/proxy"
	"fabric/internal/repository"
	"fabric/internal/router"
	"fabric/internal/server"
	"fabric/internal/service"
	"fabric/internal/storage/postgres"
	"fabric/logger"
	"fabric/sensitive"

	pbconnect "fabric/gen/protoconnect"

	"github.com/fsnotify/fsnotify"
	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/lib/pq"
	"github.com/spf13/viper"
	"go.uber.org/zap"
)

func main() {
	// get workDir
	path, err := os.Executable()
	if err != nil {
		log.Fatalf("Get working directory error: %v", err)
	}
	workDir := filepath.Dir(path)

	// get runPath
	runPath, err := os.Getwd()
	if err != nil {
		log.Fatalf("Get run path error: %v", err)
	}

	// init viper
	viper.SetConfigName("config")
	viper.SetConfigType("yaml")
	viper.AddConfigPath(filepath.Join(runPath, "configs"))
	viper.AddConfigPath(workDir)
	viper.AddConfigPath(".")
	if err := viper.ReadInConfig(); err != nil {
		log.Fatalf("Can not read in config file: %v", err)
	}
	viper.OnConfigChange(func(in fsnotify.Event) {
		if err := viper.ReadInConfig(); err != nil {
			log.Fatalf("Can not read in config file when file content was change: %v", err)
		}
	})
	viper.WatchConfig()

	// init config
	cfg, err := config.Load(workDir, runPath)
	if err != nil {
		log.Fatalf("load config file error: %v", err)
	}

	// init zap
	zapLogger := logger.NewLogger(cfg)
	zap.ReplaceGlobals(zapLogger)
	defer zapLogger.Sync()

	// init sensitive word detect
	var textPolicy proxy.TextPolicy = proxy.NoopTextPolicy{}
	if cfg.SensitiveWD {
		words, err := sensitive.LoadWordsFromConfig(cfg)
		if err != nil {
			zap.S().Fatalf("load sensitive words error: %v", err)
		}
		textPolicy = sensitive.NewTextPolicy(sensitive.NewDetector(words))
	}

	// db con str
	dsn := config.GetDSN(cfg.DB)

	// migrate
	if err := runMigrations(dsn); err != nil {
		zap.S().Warnf("migration warning: %v", err)
	}

	// init db engine
	db, err := sql.Open("postgres", dsn)
	if err != nil {
		zap.S().Fatalf("failed to open database: %v", err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		zap.S().Fatalf("failed to ping database: %v", err)
	}
	db.SetMaxIdleConns(cfg.DB.MaxIdle)
	db.SetMaxOpenConns(cfg.DB.MaxOpen)
	db.SetConnMaxLifetime(cfg.DB.MaxLifeTime)

	// repo generated by sqlc
	queries := repository.New(db)

	apiKeySvc := service.NewApiKeyService(db)
	channelSvc := service.NewChannelService(db)
	modelSvc := service.NewModelService(db)
	usageSvc := service.NewUsageService(db)
	srv := server.NewServer(apiKeySvc, channelSvc, modelSvc, usageSvc)

	// register proxy
	proxyStore := postgres.NewProxyStore(queries)
	openaiUsageHandler := openaiusage.NewHandler(proxyStore)
	openaiProxy := proxy.NewOpenAIProxy(proxy.OpenAIProxyOptions{
		ModelStore:   proxyStore,
		UsageHandler: newOpenAIUsageAdapter(openaiUsageHandler),
		TextPolicy:   textPolicy,
	})

	rt := router.New(queries, openaiProxy)
	proxyMux := rt.RegisterProxyRoutes()

	go func() {
		zap.S().Infof("Proxy server listening on %s", cfg.ProxyAddr)
		if err := http.ListenAndServe(cfg.ProxyAddr, proxyMux); err != nil {
			zap.S().Fatalf("proxy server: %v", err)
		}
	}()

	adminMux := http.NewServeMux()
	apiKeyPath, apiKeyHandler := pbconnect.NewManageApiKeyServiceHandler(srv)
	usagePath, usageHandler := pbconnect.NewUsageServiceHandler(srv)
	channelPath, channelHandler := pbconnect.NewChannelServiceHandler(srv)
	modelPath, modelHandler := pbconnect.NewModelServiceHandler(srv)
	adminMux.Handle(apiKeyPath, apiKeyHandler)
	adminMux.Handle(usagePath, usageHandler)
	adminMux.Handle(channelPath, channelHandler)
	adminMux.Handle(modelPath, modelHandler)

	zap.S().Infof("Admin server listening on %s", cfg.AdminAddr)
	if err := http.ListenAndServe(cfg.AdminAddr, adminMux); err != nil {
		zap.S().Fatalf("admin server: %v", err)
	}
}

func runMigrations(databaseURL string) error {
	m, err := migrate.New("file://db/migrations", databaseURL)
	if err != nil {
		return fmt.Errorf("migrate init: %w", err)
	}
	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
		return fmt.Errorf("migrate up: %w", err)
	}
	return nil
}
