package main

import (
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/HyperToken-dev/fabric/business/sensitive"
	"github.com/HyperToken-dev/fabric/internal/config"
	"github.com/HyperToken-dev/fabric/internal/models"
	"github.com/HyperToken-dev/fabric/internal/repository"
	"github.com/HyperToken-dev/fabric/internal/router"
	"github.com/HyperToken-dev/fabric/internal/server"
	"github.com/HyperToken-dev/fabric/internal/service"
	"github.com/HyperToken-dev/fabric/internal/storage/postgres"
	webui "github.com/HyperToken-dev/fabric/internal/web"
	"github.com/HyperToken-dev/fabric/logger"

	pbconnect "github.com/HyperToken-dev/fabric/gen/protoconnect"

	"github.com/fsnotify/fsnotify"
	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/lib/pq"
	"github.com/spf13/viper"
	"go.uber.org/zap"
)

func main() {
	// get workDir
	path, err := os.Executable()
	if err != nil {
		log.Fatalf("Get working directory error: %v", err)
	}
	workDir := filepath.Dir(path)

	// get runPath
	runPath, err := os.Getwd()
	if err != nil {
		log.Fatalf("Get run path error: %v", err)
	}

	// init viper
	viper.SetConfigName("config")
	viper.SetConfigType("yaml")
	viper.AddConfigPath(filepath.Join(runPath, "configs"))
	viper.AddConfigPath(workDir)
	viper.AddConfigPath(".")
	if err := viper.ReadInConfig(); err != nil {
		log.Fatalf("Can not read in config file: %v", err)
	}
	viper.OnConfigChange(func(in fsnotify.Event) {
		if err := viper.ReadInConfig(); err != nil {
			log.Fatalf("Can not read in config file when file content was change: %v", err)
		}
	})
	viper.WatchConfig()

	// init config
	cfg, err := config.Load(workDir, runPath)
	if err != nil {
		log.Fatalf("load config file error: %v", err)
	}

	// init zap
	zapLogger := logger.NewLogger(cfg)
	zap.ReplaceGlobals(zapLogger)
	defer func() {
		if err := zapLogger.Sync(); err != nil {
			log.Printf("sync logger error: %v", err)
		}
	}()
	zap.L().Info("configuration loaded",
		zap.String("proxy_addr", cfg.ProxyAddr),
		zap.String("admin_addr", cfg.AdminAddr),
		zap.Bool("sensitive_word_detect", cfg.SensitiveWD),
	)

	// init sensitive word detect
	var textPolicy TextPolicy = NoopTextPolicy{}
	if cfg.SensitiveWD {
		dictPath := sensitiveWordsPath(cfg.WorkDir, cfg.RunPath)
		detector, err := loadSensitiveDetector(dictPath, cfg.SensitiveDictionaries)
		if err != nil {
			zap.S().Fatalf("load sensitive dictionaries error: %v", err)
		}
		textPolicy = sensitive.NewTextPolicy(detector)
		zap.L().Info("sensitive dictionaries loaded", zap.String("path", dictPath), zap.Int("count", len(cfg.SensitiveDictionaries)))
	} else {
		zap.L().Info("sensitive word detection disabled")
	}

	// db con str
	dsn := config.GetDSN(cfg.DB)

	// migrate
	zap.L().Info("database migration started")
	if err := runMigrations(dsn); err != nil {
		zap.S().Warnf("migration warning: %v", err)
	} else {
		zap.L().Info("database migration completed")
	}

	// init db engine
	db, err := sql.Open("postgres", dsn)
	if err != nil {
		zap.S().Fatalf("failed to open database: %v", err)
	}
	defer db.Close()

	if err := db.Ping(); err != nil {
		zap.S().Fatalf("failed to ping database: %v", err)
	}
	db.SetMaxIdleConns(cfg.DB.MaxIdle)
	db.SetMaxOpenConns(cfg.DB.MaxOpen)
	db.SetConnMaxLifetime(cfg.DB.MaxLifeTime)
	zap.L().Info("database connected",
		zap.Int("max_idle", cfg.DB.MaxIdle),
		zap.Int("max_open", cfg.DB.MaxOpen),
		zap.Duration("max_lifetime", cfg.DB.MaxLifeTime),
	)

	// repo generated by sqlc
	queries := repository.New(db)

	apiKeySvc := service.NewApiKeyService(db)
	channelSvc := service.NewChannelService(db)
	modelSvc := service.NewModelService(db)
	usageSvc := service.NewUsageService(db, cfg.Location)
	srv := server.NewServer(apiKeySvc, channelSvc, modelSvc, usageSvc)

	// register proxy
	proxyStore := postgres.NewProxyStore(queries)
	openaiProxy, err := NewOpenAIProxy(OpenAIProxyOptions{
		ModelStore:   newModelStoreAdapter(proxyStore),
		UsageHandler: newOpenAIUsageAdapter(proxyStore),
		TextPolicy:   textPolicy,
	})
	if err != nil {
		zap.S().Fatalf("create openai proxy error: %v", err)
	}
	alibabaBailianProxy, err := NewAlibabaBailianProxy(AlibabaBailianProxyOptions{
		ModelStore: newModelStoreAdapter(proxyStore),
	})
	if err != nil {
		zap.S().Fatalf("create alibaba bailian proxy error: %v", err)
	}

	rt := router.New(queries, map[int32]router.Proxy{
		models.APIFormatOpenAI:         openaiProxy,
		models.APIFormatAlibabaBailian: alibabaBailianProxy,
	})
	proxyMux := rt.RegisterProxyRoutes()
	zap.L().Info("proxy routes registered")

	go func() {
		zap.S().Infof("Proxy server listening on %s", cfg.ProxyAddr)
		if err := http.ListenAndServe(cfg.ProxyAddr, proxyMux); err != nil {
			zap.S().Fatalf("proxy server: %v", err)
		}
	}()

	adminMux := http.NewServeMux()
	apiKeyPath, apiKeyHandler := pbconnect.NewManageApiKeyServiceHandler(srv)
	usagePath, usageHandler := pbconnect.NewUsageServiceHandler(srv)
	channelPath, channelHandler := pbconnect.NewChannelServiceHandler(srv)
	modelPath, modelHandler := pbconnect.NewModelServiceHandler(srv)
	adminMux.Handle(apiKeyPath, apiKeyHandler)
	adminMux.Handle(usagePath, usageHandler)
	adminMux.Handle(channelPath, channelHandler)
	adminMux.Handle(modelPath, modelHandler)
	zap.L().Info("admin handlers registered",
		zap.String("api_key_path", apiKeyPath),
		zap.String("usage_path", usagePath),
		zap.String("channel_path", channelPath),
		zap.String("model_path", modelPath),
	)

	zap.S().Infof("Admin server listening on %s", cfg.AdminAddr)
	if err := http.ListenAndServe(cfg.AdminAddr, webui.Handler(adminMux)); err != nil {
		zap.S().Fatalf("admin server: %v", err)
	}
}

func runMigrations(databaseURL string) error {
	m, err := migrate.New("file://db/migrations", databaseURL)
	if err != nil {
		return fmt.Errorf("migrate init: %w", err)
	}
	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
		return fmt.Errorf("migrate up: %w", err)
	}
	return nil
}

func sensitiveWordsPath(workDir, runPath string) string {
	path := filepath.Join(workDir, "stwd")
	if info, err := os.Stat(path); err == nil && info.IsDir() {
		return path
	}
	return filepath.Join(runPath, "configs", "stwd")
}

func loadSensitiveDetector(dir string, configs []config.SensitiveDictionaryConfig) (*sensitive.Detector, error) {
	dictionaries := make([]sensitive.Dictionary, 0, len(configs))
	for _, dictConfig := range configs {
		name := strings.TrimSpace(dictConfig.Name)
		if name == "" {
			return nil, fmt.Errorf("sensitive dictionary name is required")
		}
		if len(dictConfig.KeywordFileList) == 0 {
			return nil, fmt.Errorf("sensitive dictionary %q keywordFileList is required", name)
		}

		dict := sensitive.Dictionary{
			Name:         name,
			EffectModels: append([]string(nil), dictConfig.EffectModels...),
		}
		for _, fileName := range dictConfig.KeywordFileList {
			fileName = strings.TrimSpace(fileName)
			if fileName == "" || filepath.Base(fileName) != fileName || fileName == "." || fileName == ".." {
				return nil, fmt.Errorf("invalid sensitive keyword file name %q", fileName)
			}
			loaded, err := sensitive.LoadDictionary(name, filepath.Join(dir, fileName+".txt"), dictConfig.EffectModels)
			if err != nil {
				return nil, err
			}
			dict.Words = append(dict.Words, loaded.Words...)
		}
		dictionaries = append(dictionaries, dict)
	}
	return sensitive.NewDetector(dictionaries...)
}
